config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  post 'appointments/:id/evaluations/:id', to: 'evaluations#create'
  root to: 'appointments#index' 
  resources :checks
  resources :admins, only: [:index, :show]
  resources :appointments do
   resources :evaluations, only: [:index, :create, :edit, :update]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/evaluation.rb
class Evaluation < ApplicationRecord
  belongs_to :user
  belongs_to :appointment

  validates :comment, length: {maximum: 250}
end

app/controllers/evaluations_controller.rb
class EvaluationsController < ApplicationController
  
  protect_from_forgery :except => [:create, :update]

  def index
    @users = User.all.order("created_at DESC")
    @checks = Check.all
    checks = @checks
    @mychecks = current_user.checks
  end

  def edit
    @appointment = Appointment.find(params[:appointment_id])
    @evaluation = Evaluation.find_by(appointment_id:@appointment.id)
  end

  def create
    @evaluation = Evaluation.find_or_initialize_by(appointment_id: new_evaluation_params[:appointment_id])
    if @evaluation.new_record?
      @evaluation = Evaluation.new(new_evaluation_params)
      @evaluation.save!
       redirect_to "/admins/#{@evaluation.appointment.user.id}"
    else
      render :edit
    end
  end

  def update
    @evaluation = Evaluation.find_or_initialize_by(appointment_id: evaluation_params[:appointment_id])
    if @evaluation.update(evaluation_params)
      redirect_to "/admins/#{@evaluation.appointment.user.id}"
    else
      render :edit
    end
  end

  private

  def evaluation_params
    params.require(:evaluation)
    .permit(
      :point1, :point2, :point3, :point4, :point5, 
      :point6, :point7, :point8, :point9, :point10,
      :point11, :point12, :point13, :point14, :point15, 
      :point16, :point17, :point18, :point19, :point20, :comment)
   .merge(user_id: current_user.id,appointment_id:params[:appointment_id])  
  end

  def new_evaluation_params
    params
    .permit(
      :point1, :point2, :point3, :point4, :point5, 
      :point6, :point7, :point8, :point9, :point10,
      :point11, :point12, :point13, :point14, :point15, 
      :point16, :point17, :point18, :point19, :point20, :comment)
   .merge(user_id: current_user.id,appointment_id:params[:appointment_id])  
  end



end

app/helpers/evaluations_helper.rb
module EvaluationsHelper
end

app/views/evaluations/edit.html.erb
<div class="relative">
  <%= render "shared/header" %>

  <%#評価コメントが入っていなかったらこっち%>
  <%if @evaluation.nil?%> 
  <div class="input-contents">  
    <div class="input-main">
      <h2 class="input-title"><%= @appointment.company %></h2>
      <%= form_with model: @evaluation, url: appointment_evaluations_path, local: true do |f| %>

      <div class="new-appt">
        チェック項目
       <br> <span class="annotation">※点数は0~5点（半角）で入力してください</span>
      </div>

      <%# チェックリスト %>
      <table class='table-check'>
        <tr class='check-list-title'><th colspan="2"><%= @appointment.check.title%></th></tr>
        <tr class='check-list'><th class="th-title"><%="チェック項目" %></th><th><%="点数" %></th></tr>
        <tr><td><%= @appointment.check.item1%></td><td><%= f.number_field :point1, id:"item1",class:"point", min: 0, max: 5 %>点</td></tr>
        <tr><td><%= @appointment.check.item2%></td><td><%= f.number_field :point2, id:"item2",class:"point", min: 0, max: 5 %>点</td></tr>
        <tr><td><%= @appointment.check.item3%></td><td><%= f.number_field :point3, id:"item3",class:"point", min: 0, max: 5 %>点</td></tr>
        <tr><td><%= @appointment.check.item4%></td><td><%= f.number_field :point4, id:"item4",class:"point", min: 0, max: 5  %>点</td></tr>
        <tr><td><%= @appointment.check.item5%></td><td><%= f.number_field :point5, id:"item5",class:"point", min: 0, max: 5  %>点</td></tr>
        <tr><td><%= @appointment.check.item6%></td><td><%= f.number_field :point6, id:"item6",class:"point", min: 0, max: 5  %>点</td></tr>
        <tr><td><%= @appointment.check.item7%></td><td><%= f.number_field :point7, id:"item7",class:"point", min: 0, max: 5  %>点</td></tr>
        <tr><td><%= @appointment.check.item8%></td><td><%= f.number_field :point8, id:"item8",class:"point", min: 0, max: 5  %>点</td></tr>
        <tr><td><%= @appointment.check.item9%></td><td><%= f.number_field :point9, id:"item9",class:"point", min: 0, max: 5  %>点</td></tr>
        <tr><td><%= @appointment.check.item10%></td><td><%= f.number_field :point10, id:"item10",class:"point", min: 0, max: 5  %>点</td></tr>
        <tr><td><%= @appointment.check.item11%></td><td><%= f.number_field :point11, id:"item11",class:"point", min: 0, max: 5 %>点</td></tr>
        <tr><td><%= @appointment.check.item12%></td><td><%= f.number_field :point12, id:"item12",class:"point", min: 0, max: 5  %>点</td></tr>
        <tr><td><%= @appointment.check.item13%></td><td><%= f.number_field :point13, id:"item13",class:"point", min: 0, max: 5  %>点</td></tr>
        <tr><td><%= @appointment.check.item14%></td><td><%= f.number_field :point14, id:"item14",class:"point", min: 0, max: 5  %>点</td></tr>
        <tr><td><%= @appointment.check.item15%></td><td><%= f.number_field :point15, id:"item15",class:"point", min: 0, max: 5  %>点</td></tr>
        <tr><td><%= @appointment.check.item16%></td><td><%= f.number_field :point16, id:"item16",class:"point", min: 0, max: 5  %>点</td></tr>
        <tr><td><%= @appointment.check.item17%></td><td><%= f.number_field :point17, id:"item17",class:"point", min: 0, max: 5  %>点</td></tr>
        <tr><td><%= @appointment.check.item18%></td><td><%= f.number_field :point18, id:"item18",class:"point", min: 0, max: 5  %>点</td></tr>
        <tr><td><%= @appointment.check.item19%></td><td><%= f.number_field :point19, id:"item19",class:"point", min: 0, max: 5  %>点</td></tr>
        <tr><td><%= @appointment.check.item20%></td><td><%= f.number_field :point20, id:"item20",class:"point", min: 0, max: 5  %>点</td></tr>
      </table>

      <button  type="button", id= "addition", class="addition">合計</button><span id='score', class="score"></span>点

      <div class="weight-bold-text">
        コメント
        <br> <%= f.text_area :comment, class:"appt_comment", id:"content"%>
      </div>

      <div class="input-btn-contents">
        <%= f.submit "更新", class:"appt-input-btn" %>
        <%=link_to 'もどる', :back, class:"back-btn" %>
      </div>

      <% end %> 
    </div>
  </div>

  <%#評価コメントが入っていたらこっち%>
  <%else%>
  <div class="input-contents">  
    <div class="input-main">
      <h2 class="input-title"><%= @appointment.company %></h2>
      <%= form_with model: @evaluation, url: appointment_evaluation_path, local: true do |f| %>

      <div class="new-appt">
        チェック項目
       <br> <span class="annotation">※点数は0~5点（半角）で入力してください</span>
      </div>

      <%# チェックリスト %>
      <table class='table-check'>
        <tr class='check-list-title'><th colspan="2"><%= @appointment.check.title%></th></tr>
        <tr class='check-list'><th class="th-title"><%="チェック項目" %></th><th><%="点数" %></th></tr>
        <tr><td><%= @appointment.check.item1%></td><td><%= f.number_field :point1, id:"item1",class:"point", min: 0, max: 5 %>点</td></tr>
        <tr><td><%= @appointment.check.item2%></td><td><%= f.number_field :point2, id:"item2",class:"point", min: 0, max: 5 %>点</td></tr>
        <tr><td><%= @appointment.check.item3%></td><td><%= f.number_field :point3, id:"item3",class:"point", min: 0, max: 5 %>点</td></tr>
        <tr><td><%= @appointment.check.item4%></td><td><%= f.number_field :point4, id:"item4",class:"point", min: 0, max: 5  %>点</td></tr>
        <tr><td><%= @appointment.check.item5%></td><td><%= f.number_field :point5, id:"item5",class:"point", min: 0, max: 5  %>点</td></tr>
        <tr><td><%= @appointment.check.item6%></td><td><%= f.number_field :point6, id:"item6",class:"point", min: 0, max: 5  %>点</td></tr>
        <tr><td><%= @appointment.check.item7%></td><td><%= f.number_field :point7, id:"item7",class:"point", min: 0, max: 5  %>点</td></tr>
        <tr><td><%= @appointment.check.item8%></td><td><%= f.number_field :point8, id:"item8",class:"point", min: 0, max: 5  %>点</td></tr>
        <tr><td><%= @appointment.check.item9%></td><td><%= f.number_field :point9, id:"item9",class:"point", min: 0, max: 5  %>点</td></tr>
        <tr><td><%= @appointment.check.item10%></td><td><%= f.number_field :point10, id:"item10",class:"point", min: 0, max: 5  %>点</td></tr>
        <tr><td><%= @appointment.check.item11%></td><td><%= f.number_field :point11, id:"item11",class:"point", min: 0, max: 5 %>点</td></tr>
        <tr><td><%= @appointment.check.item12%></td><td><%= f.number_field :point12, id:"item12",class:"point", min: 0, max: 5  %>点</td></tr>
        <tr><td><%= @appointment.check.item13%></td><td><%= f.number_field :point13, id:"item13",class:"point", min: 0, max: 5  %>点</td></tr>
        <tr><td><%= @appointment.check.item14%></td><td><%= f.number_field :point14, id:"item14",class:"point", min: 0, max: 5  %>点</td></tr>
        <tr><td><%= @appointment.check.item15%></td><td><%= f.number_field :point15, id:"item15",class:"point", min: 0, max: 5  %>点</td></tr>
        <tr><td><%= @appointment.check.item16%></td><td><%= f.number_field :point16, id:"item16",class:"point", min: 0, max: 5  %>点</td></tr>
        <tr><td><%= @appointment.check.item17%></td><td><%= f.number_field :point17, id:"item17",class:"point", min: 0, max: 5  %>点</td></tr>
        <tr><td><%= @appointment.check.item18%></td><td><%= f.number_field :point18, id:"item18",class:"point", min: 0, max: 5  %>点</td></tr>
        <tr><td><%= @appointment.check.item19%></td><td><%= f.number_field :point19, id:"item19",class:"point", min: 0, max: 5  %>点</td></tr>
        <tr><td><%= @appointment.check.item20%></td><td><%= f.number_field :point20, id:"item20",class:"point", min: 0, max: 5  %>点</td></tr>
      </table>
      <button  type="button", id= "addition", class="addition">合計</button><span id='score', class="score"></span>点

      <div class="weight-bold-text">
        コメント(最大250文字)
        <br> <%= f.text_area :comment, class:"appt_comment", id:"content"%>
      </div>


      <div class="input-btn-contents">
        <%= f.submit "更新", class:"appt-input-btn" %>
        <%=link_to 'もどる', :back, class:"back-btn" %>
      </div>

      <% end %> 
    </div>
  </div>

  <%end%>

  <%= render "shared/footer" %>
</div>

app/views/evaluations/new.html.erb
<div class="relative">
  <%= render "shared/header" %>

  <div class="input-contents">  
    <div class="input-main">
      <h2 class="input-title"><%= @appointment.company %></h2>
      <%= form_with model: Evaluation.new, url: appointment_evaluations_path, local: true do |f| %>


      <div class="new-appt">
        チェック項目
       <br> <span class="annotation">※点数は0~5点（半角）で入力してください</span>
      </div>

      <%# チェックリスト %>
      <table class='table-check'>
        <tr class='check-list-title'><th colspan="2"><%= @appointment.check.title%></th></tr>
        <tr class='check-list'><th class="th-title"><%="チェック項目" %></th><th><%="点数" %></th></tr>
        <tr><td><%= @appointment.check.item1%></td><td><%= f.number_field :point1, id:"item1",class:"point", min: 0, max: 5 %>点</td></tr>
        <tr><td><%= @appointment.check.item2%></td><td><%= f.number_field :point2, id:"item2",class:"point", min: 0, max: 5 %>点</td></tr>
        <tr><td><%= @appointment.check.item3%></td><td><%= f.number_field :point3, id:"item3",class:"point", min: 0, max: 5 %>点</td></tr>
        <tr><td><%= @appointment.check.item4%></td><td><%= f.number_field :point4, id:"item4",class:"point", min: 0, max: 5  %>点</td></tr>
        <tr><td><%= @appointment.check.item5%></td><td><%= f.number_field :point5, id:"item5",class:"point", min: 0, max: 5  %>点</td></tr>
        <tr><td><%= @appointment.check.item6%></td><td><%= f.number_field :point6, id:"item6",class:"point", min: 0, max: 5  %>点</td></tr>
        <tr><td><%= @appointment.check.item7%></td><td><%= f.number_field :point7, id:"item7",class:"point", min: 0, max: 5  %>点</td></tr>
        <tr><td><%= @appointment.check.item8%></td><td><%= f.number_field :point8, id:"item8",class:"point", min: 0, max: 5  %>点</td></tr>
        <tr><td><%= @appointment.check.item9%></td><td><%= f.number_field :point9, id:"item9",class:"point", min: 0, max: 5  %>点</td></tr>
        <tr><td><%= @appointment.check.item10%></td><td><%= f.number_field :point10, id:"item10",class:"point", min: 0, max: 5  %>点</td></tr>
        <tr><td><%= @appointment.check.item11%></td><td><%= f.number_field :point11, id:"item11",class:"point", min: 0, max: 5 %>点</td></tr>
        <tr><td><%= @appointment.check.item12%></td><td><%= f.number_field :point12, id:"item12",class:"point", min: 0, max: 5  %>点</td></tr>
        <tr><td><%= @appointment.check.item13%></td><td><%= f.number_field :point13, id:"item13",class:"point", min: 0, max: 5  %>点</td></tr>
        <tr><td><%= @appointment.check.item14%></td><td><%= f.number_field :point14, id:"item14",class:"point", min: 0, max: 5  %>点</td></tr>
        <tr><td><%= @appointment.check.item15%></td><td><%= f.number_field :point15, id:"item15",class:"point", min: 0, max: 5  %>点</td></tr>
        <tr><td><%= @appointment.check.item16%></td><td><%= f.number_field :point16, id:"item16",class:"point", min: 0, max: 5  %>点</td></tr>
        <tr><td><%= @appointment.check.item17%></td><td><%= f.number_field :point17, id:"item17",class:"point", min: 0, max: 5  %>点</td></tr>
        <tr><td><%= @appointment.check.item18%></td><td><%= f.number_field :point18, id:"item18",class:"point", min: 0, max: 5  %>点</td></tr>
        <tr><td><%= @appointment.check.item19%></td><td><%= f.number_field :point19, id:"item19",class:"point", min: 0, max: 5  %>点</td></tr>
        <tr><td><%= @appointment.check.item20%></td><td><%= f.number_field :point20, id:"item20",class:"point", min: 0, max: 5  %>点</td></tr>
      </table>
      <button  type="button", id= "addition", class="addition">合計</button><span id='score', class="score"></span>点

      <div class="weight-bold-text">
        コメント
      <div>
      <br> <%= f.text_area :comment, class:"appt_comment", id:"content"%>
      </div>


      <div class="input-btn-contents">
        <%= f.submit "更新", class:"appt-input-btn" %>
        <%=link_to 'もどる', :back, class:"back-btn" %>
      </div>


      <% end %> 
    </div>
  </div>

  <%= render "shared/footer" %>
</div>