config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  post 'appointments/:id/evaluations/:id', to: 'evaluations#create'
  root to: 'appointments#index' 
  resources :checks
  resources :admins, only: [:index, :show]
  resources :appointments do
   resources :evaluations, only: [:index, :create, :edit, :update]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/admins/index.html.erb
<div class="relative">
  <%= render "shared/header" %>
<div class="admin-contents">

    <%# ユーザー情報 %>
  <div class="admin-user">
    <h2 class="admin-show-title">メンバー情報</h2>
    <% unless  @mychecks.length == 0 %>
    <table class='table-lists' >
      <h2 class="my-list">登録済みメンバー一覧</h2>
      <tr class="company-lists"><th colspan="3">メンバー</th></tr>
      <tr class='company-list'>
        <th class="th-title"><%="名前" %></th><th><%="入社年" %></th><th><%="詳細" %></th>
      </tr>
      <% @users.each do |user| %>
      <tr class="list", id="list">
        <td><%= user.name %></td>
        <td><%= user.joined %>年</td>
        <td><%= link_to image_tag('eye.jpg', :size => '20x20' ),  admin_path(user.id), class: "appt-red-btn" %></td>
      </tr>
      <% end %>
    </table>
    <%end%>
  </div>

  <%# チェックリスト %>
  <div class="admin-check">
    <h2 class="admin-show-title">チェックリスト<%= link_to 'リスト追加', new_check_path, class: "check-new-btn", id: "btn2" %></h2>
   
    <% unless  @mychecks.length == 0 %>
    <table class='table-lists' >
      <h2 class="my-list">自分が登録したチェックリスト</h2>
      <tr class="company-lists"><th colspan="3">チェックリスト</th></tr>
      <tr class='company-list'>
        <th class="th-title"><%="タイトル" %></th><th><%="編集" %></th><th><%="削除" %></th>
      </tr>
      <% @mychecks.each do |check| %>
      <tr class="list", id="list">
        <td><%= check.title %></td>
        <td><%= link_to image_tag('pen.jpg', :size => '20x20' ), edit_check_path(check.id), class: "appt-red-btn" %></td>
        <td><% if check.id != 1%><%= link_to image_tag('gomi.jpg', :size => '20x20' ),check_path(check.id), method: :delete, class: "delete-btn", data: { confirm: 'このチェックリストを利用している商談情報も合わせて削除されます。本当に削除してもいいですか？' } %><%end%></td>
      </tr>
      <% end %>
    </table>
    <%end%>
  </div>

</div>
  <%= render "shared/footer" %>
</div>

app/views/admins/show.html.erb
<div class="relative">
  <%= render "shared/header" %>

  <div class="member">
    <h2 class="member-title"><%= "#{@user.name}さんのページを表示しています" %></h2>  
    <%# アポ 一覧 %>
    <table class='table-lists' >
      <tr class="company-lists"><th colspan="6"><%= "登録済み顧客一覧" %></th></tr>
      <tr class='company-list'>
        <th class="td-date"><%="約束日" %></th><th class="td-company"><%="社名" %></th><th class="td-result"><%="結論" %></th><th class="td-score"><%="点数" %></th><th><%="詳細"%></th><th><%="評価"%></th>
      </tr>
      <%# 結果未入力アポ %>
      <tr class="company-lists-sub"><th colspan="6">結果未入力</th></tr>
      <%@appointment1.each do |appointment1|  %>
      <tr class="list", id="list">
        <td><%= appointment1.appt_date %></td>
        <td><%= appointment1.company %></td>
        <td><%= appointment1.result.name if appointment1.result %></td>
        <td><%= appointment1.score %>点</td>
        <td><%= link_to image_tag('eye.jpg', :size => '20x20' ), appointment_path(appointment1.id), class: "appt-red-btn" %></td>
        <td><%= link_to image_tag('pen.jpg', :size => '20x20' ), edit_appointment_evaluation_path(appointment1.id), class: "appt-red-btn" %></td>
      </tr>
      <% end %>
      <%# 受注済みアポ %>
      <tr class="company-lists-sub"><th colspan="6">受注済み</th></tr>
      <%@appointment2.each do |appointment2|  %>
      <tr class="list", id="list">
        <td><%= appointment2.appt_date %></td>
        <td><%= appointment2.company %></td>
        <td><%= appointment2.result.name if appointment2.result %></td>
        <td><%= appointment2.score %>点</td>
        <td><%= link_to image_tag('eye.jpg', :size => '20x20' ), appointment_path(appointment2.id), class: "appt-red-btn" %></td>
        <td><%= link_to image_tag('pen.jpg', :size => '20x20' ), edit_appointment_evaluation_path(appointment2.id), class: "appt-red-btn" %></td>     </tr>
      <% end %>
      <%# 失注アポ %>
      <tr class="company-lists-sub"><th colspan="6">失注</th></tr>
      <%@appointment3.each do |appointment3|  %>
      <tr class="list", id="list">
        <td><%= appointment3.appt_date %></td>
        <td><%= appointment3.company %></td>
        <td><%= appointment3.result.name if appointment3.result %></td>
        <td><%= appointment3.score %>点</td>
        <td><%= link_to image_tag('eye.jpg', :size => '20x20' ), appointment_path(appointment3.id), class: "appt-red-btn" %></td>
        <td><%= link_to image_tag('pen.jpg', :size => '20x20' ), edit_appointment_evaluation_path(appointment3.id), class: "appt-red-btn" %></td>        </td>
      </tr>
      <% end %>
      <%# 検討中アポ %>
      <tr class="company-lists-sub"><th colspan="6">検討中</th></tr>
      <%@appointment4.each do |appointment4|  %>
      <tr class="list", id="list">
        <td><%= appointment4.appt_date %></td>
        <td><%= appointment4.company %></td>
        <td><%= appointment4.result.name if appointment4.result %></td>
        <td><%= appointment4.score %>点</td>
        <td><%= link_to image_tag('eye.jpg', :size => '20x20' ), appointment_path(appointment4.id), class: "appt-red-btn" %></td>
        <td><%= link_to image_tag('pen.jpg', :size => '20x20' ), edit_appointment_evaluation_path(appointment4.id), class: "appt-red-btn" %></td>
      </tr>
      <% end %>
    </table>
 
  </div>
  <%= render "shared/footer" %>
</div>