config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  post 'appointments/:id/evaluations/:id', to: 'evaluations#create'
  root to: 'appointments#index' 
  resources :checks
  resources :admins, only: [:index, :show]
  resources :appointments do
   resources :evaluations, only: [:index, :create, :edit, :update]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :user
  belongs_to :check
  has_one :evaluations

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :result, optional: true
  
  with_options presence: true do
    validates :company
    validates :appt_date
    validates :check_id, numericality: true
  end
  validates :comment, length: {maximum: 250}
  validates :score, numericality: { only_integer: true, greater_than:0, less_than: 101}, allow_blank: true

end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :authenticate_user!, except: [:index ]
  before_action :get_cheak

  def index
    @appointments =Appointment.all
    @checks = Check.all
  end

  def new
    @checks = Check.all
    @appointment = Appointment.all.order(appt_date: "DESC")
    appointment = @appointment
    @appointment = current_user.appointments
    @appointment1 = Appointment.where(result_id: [nil, 1], user_id: current_user.id ).order(appt_date: "DESC")
    @appointment2 = Appointment.where(result_id: 2, user_id: current_user.id ).order(appt_date: "DESC")
    @appointment3 = Appointment.where(result_id: 3, user_id: current_user.id ).order(appt_date: "DESC")
    @appointment4 = Appointment.where(result_id: 4, user_id: current_user.id ).order(appt_date: "DESC")
  end

  def create
   appointment = Appointment.new(appointment_params)
   @checks = Check.all.to_json
    if appointment.save
      render json:{ post: appointment }
    else
       render :new
    end
  end


  def edit
    @appointment = Appointment.find(params[:id])
    redirect_to action: :new if @appointment.user_id != current_user.id 
  end

  def show
    @appointment = Appointment.find(params[:id])
    @evaluation = Evaluation.find_by(appointment_id:@appointment.id)
  end

  def update
    @appointment = Appointment.find(params[:id])
    if @appointment.update(appointment_params)
      redirect_to new_appointment_path
    else
      render :edit
    end
  end

  def destroy
    @appointment = Appointment.find(params[:id])
    if @appointment.user_id == current_user.id
       @appointment.destroy
       redirect_to action: :new
    else
      redirect_to action: :index
    end
  end

  private
  def appointment_params
    params.require(:appointment)
    .permit(:company, :appt_date, :result_id, :score, :check_id,
       :point1, :point2, :point3, :point4, :point5, 
       :point6, :point7, :point8, :point9, :point10,
       :point11, :point12, :point13, :point14, :point15, 
       :point16, :point17, :point18, :point19, :point20, :comment)
    .merge(user_id: current_user.id)
  end

  def get_cheak
    @checks = Check.all.to_json
  end

end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/edit.html.erb
<div class="relative">
  <%= render "shared/header" %>

  <div class="input-contents">  
    <div class="input-main">
      <h2 class="input-title">詳細入力画面</h2>
      <%= form_with model: @appointment, url: appointment_path, local: true do |f| %>
      <%= render 'shared/error_messages', model: f.object %>

      <%# アポ情報登録 %>
      <div class="new-appt">
        <div class="weight-bold-text">
          社名
          <%= f.text_area :company, class:"appt_content", id:"content", placeholder:"株式会社〇〇" %>
        </div>
        <div class="weight-bold-text">
          約束日
          <%= f.date_field :appt_date, id:"content", class:"appt_content" %>
        </div>
      </div>
      <div class="weight-bold-text">
        結論
        <%= f.collection_select(:result_id, Result.all, :id, :name, {}, {class:"appt_content", id:"item-category"}) %>
        チェック項目
        <%= f.collection_select :check_id, Check.all, :id, :title %><span class="indispensable">５段階評価</span>
       <br> <span class="annotation">※点数は0~5点（半角）で入力してください</span>
      </div>

      <%# チェックリスト %>
      <table class='table-check'>
        <tr class='check-list-title'><th colspan="2"><%= @appointment.check.title%></th></tr>
        <tr class='check-list'><th class="th-title"><%="チェック項目" %></th><th><%="点数" %></th></tr>
        <tr><td><%= @appointment.check.item1%></td><td><%= f.number_field :point1, id:"item1",class:"point", min: 0, max: 5 %>点</td></tr>
        <tr><td><%= @appointment.check.item2%></td><td><%= f.number_field :point2, id:"item2",class:"point", min: 0, max: 5 %>点</td></tr>
        <tr><td><%= @appointment.check.item3%></td><td><%= f.number_field :point3, id:"item3",class:"point", min: 0, max: 5 %>点</td></tr>
        <tr><td><%= @appointment.check.item4%></td><td><%= f.number_field :point4, id:"item4",class:"point", min: 0, max: 5  %>点</td></tr>
        <tr><td><%= @appointment.check.item5%></td><td><%= f.number_field :point5, id:"item5",class:"point", min: 0, max: 5  %>点</td></tr>
        <tr><td><%= @appointment.check.item6%></td><td><%= f.number_field :point6, id:"item6",class:"point", min: 0, max: 5  %>点</td></tr>
        <tr><td><%= @appointment.check.item7%></td><td><%= f.number_field :point7, id:"item7",class:"point", min: 0, max: 5  %>点</td></tr>
        <tr><td><%= @appointment.check.item8%></td><td><%= f.number_field :point8, id:"item8",class:"point", min: 0, max: 5  %>点</td></tr>
        <tr><td><%= @appointment.check.item9%></td><td><%= f.number_field :point9, id:"item9",class:"point", min: 0, max: 5  %>点</td></tr>
        <tr><td><%= @appointment.check.item10%></td><td><%= f.number_field :point10, id:"item10",class:"point", min: 0, max: 5  %>点</td></tr>
        <tr><td><%= @appointment.check.item11%></td><td><%= f.number_field :point11, id:"item11",class:"point", min: 0, max: 5 %>点</td></tr>
        <tr><td><%= @appointment.check.item12%></td><td><%= f.number_field :point12, id:"item12",class:"point", min: 0, max: 5  %>点</td></tr>
        <tr><td><%= @appointment.check.item13%></td><td><%= f.number_field :point13, id:"item13",class:"point", min: 0, max: 5  %>点</td></tr>
        <tr><td><%= @appointment.check.item14%></td><td><%= f.number_field :point14, id:"item14",class:"point", min: 0, max: 5  %>点</td></tr>
        <tr><td><%= @appointment.check.item15%></td><td><%= f.number_field :point15, id:"item15",class:"point", min: 0, max: 5  %>点</td></tr>
        <tr><td><%= @appointment.check.item16%></td><td><%= f.number_field :point16, id:"item16",class:"point", min: 0, max: 5  %>点</td></tr>
        <tr><td><%= @appointment.check.item17%></td><td><%= f.number_field :point17, id:"item17",class:"point", min: 0, max: 5  %>点</td></tr>
        <tr><td><%= @appointment.check.item18%></td><td><%= f.number_field :point18, id:"item18",class:"point", min: 0, max: 5  %>点</td></tr>
        <tr><td><%= @appointment.check.item19%></td><td><%= f.number_field :point19, id:"item19",class:"point", min: 0, max: 5  %>点</td></tr>
        <tr><td><%= @appointment.check.item20%></td><td><%= f.number_field :point20, id:"item20",class:"point", min: 0, max: 5  %>点</td></tr>
      </table>
      <button  type="button", id= "addition", class="addition">合計</button><span id='score', class="score"></span>点

      <div class="weight-bold-text">
        点数
        <%= f.text_field :score, id:"", class:"appt_content" %>点
      </div>

      <div class="weight-bold-text">
        振り返り(最大250文字)
      <br> <%= f.text_area :comment, class:"appt_comment", id:"content", placeholder:"発見や感想をメモしましょう"%>
      </div>


      <div class="input-btn-contents">
        <%= f.submit "更新", class:"appt-input-btn" %>
        <%=link_to 'もどる', new_appointment_path, class:"back-btn" %>
      </div>

      <% end %> 
    </div>
  </div>

  <%= render "shared/footer" %>
</div>

app/views/appointments/index.html.erb
<%= render "shared/header" %>

  <div class="wrapper">
    <div class="side-bar"> 
      <div class="menu">
        <%= link_to 'アポイント情報', new_appointment_path, class: "appt-menu-btn", id: "btn1" %>
        <%= link_to 'チェックリスト一覧', checks_path, class: "appt-menu-btn", id: "btn2" %>
        <% if current_user && current_user.admin? %>
        <%= link_to '管理者ページ',  admins_path, class: "appt-menu-btn", id: "btn3" %>
        <%end%>
      </div>
    </div>

<%= render "shared/about" %> 
  
  </div>

app/views/appointments/new.html.erb
<div class="relative">
  <%= render "shared/header" %>

  <div class="appt-new">
   
    <div class="appt-input-contents">
      <div class="appt-input-main">
      <h2 class="appt-input-title">アポイント情報追加</h2>  
      <%= form_with model: @appointment, url: appointments_path, method: :post, id:"form" do |f| %>
      
        <div class="new-appt">
          <div class="weight-bold-text">
            社名<span class="indispensable">必須</span>
            <br><%= f.text_area :company, class:"appt_content", id:"content", placeholder:"株式会社〇〇" %>
          </div>
          <div class="weight-bold-text">
            約束日<span class="indispensable">必須</span>
            <br><%= f.date_field :appt_date, id:"content", class:"appt_content" %>
          </div>
          <div class="weight-bold-text">
            チェック項目<span class="indispensable">必須</span>
            <br><%= f.collection_select :check_id, Check.all, :id, :title , prompt: "選択してください", class:"appt_content"%>
          </div>

          <div class="input-btn-contents">
            <%= f.submit "登録", class:"appt-input-btn", id: "submit" %>
          </div>
        </div>
        
      <% end %> 
      </div>
    </div>

    <%# アポ 一覧 %>
    <table class='table-lists' >
      <tr class="company-lists"><th colspan="7"><%= "登録済み顧客一覧" %></th></tr>
      <tr class='company-list'>
        <th class="td-date"><%="約束日" %></th><th class="td-company"><%="社名" %></th><th class="td-result"><%="結論" %></th><th class="td-score"><%="点数" %></th><th><%="編集"%></th><th><%="詳細"%></th><th><%="削除" %></th>
      </tr>
      <%# 結果未入力アポ %>
      <tr class="company-lists-sub"><th colspan="7">結果未入力</th></tr>
      <%@appointment1.each do |appointment1|  %>
      <tr class="list", id="list">
        <td><%= appointment1.appt_date %></td>
        <td><%= appointment1.company %></td>
        <td><%= appointment1.result.name if appointment1.result %></td>
        <td><%= appointment1.score %>点</td>
        <td><%= link_to image_tag('pen.jpg', :size => '20x20' ), edit_appointment_path(appointment1.id), class: "appt-red-btn" %></td>
        <td><%= link_to image_tag('eye.jpg', :size => '20x20' ), appointment_path(appointment1.id), class: "appt-red-btn" %></td>
        <td><%= link_to image_tag('gomi.jpg', :size => '20x20' ), appointment_path(appointment1.id), method: :delete, class: "delete-btn",data: { confirm: '削除しますか？' } %></td>
      </tr>
      <% end %>
      <%# 受注済みアポ %>
      <tr class="company-lists-sub"><th colspan="7">受注済み</th></tr>
      <%@appointment2.each do |appointment2|  %>
      <tr class="list", id="list">
        <td><%= appointment2.appt_date %></td>
        <td><%= appointment2.company %></td>
        <td><%= appointment2.result.name if appointment2.result %></td>
        <td><%= appointment2.score %>点</td>
        <td><%= link_to image_tag('pen.jpg', :size => '20x20' ), edit_appointment_path(appointment2.id), class: "appt-red-btn" %></td>
        <td><%= link_to image_tag('eye.jpg', :size => '20x20' ), appointment_path(appointment2.id), class: "appt-red-btn" %></td>
        <td><%= link_to image_tag('gomi.jpg', :size => '20x20' ), appointment_path(appointment2.id), method: :delete, class: "delete-btn",data: { confirm: '削除しますか？' } %></td>
      </tr>
      <% end %>
      <%# 失注アポ %>
      <tr class="company-lists-sub"><th colspan="7">失注</th></tr>
      <%@appointment3.each do |appointment3|  %>
      <tr class="list", id="list">
        <td><%= appointment3.appt_date %></td>
        <td><%= appointment3.company %></td>
        <td><%= appointment3.result.name if appointment3.result %></td>
        <td><%= appointment3.score %>点</td>
        <td><%= link_to image_tag('pen.jpg', :size => '20x20' ), edit_appointment_path(appointment3.id), class: "appt-red-btn" %></td>
        <td><%= link_to image_tag('eye.jpg', :size => '20x20' ), appointment_path(appointment3.id), class: "appt-red-btn" %></td>
        <td><%= link_to image_tag('gomi.jpg', :size => '20x20' ), appointment_path(appointment3.id), method: :delete, class: "delete-btn",data: { confirm: '削除しますか？' } %>
        </td>
      </tr>
      <% end %>
      <%# 検討中アポ %>
      <tr class="company-lists-sub"><th colspan="7">検討中</th></tr>
      <%@appointment4.each do |appointment4|  %>
      <tr class="list", id="list">
        <td><%= appointment4.appt_date %></td>
        <td><%= appointment4.company %></td>
        <td><%= appointment4.result.name if appointment4.result %></td>
        <td><%= appointment4.score %>点</td>
        <td><%= link_to image_tag('pen.jpg', :size => '20x20' ), edit_appointment_path(appointment4.id), class: "appt-red-btn" %></td>
        <td><%= link_to image_tag('eye.jpg', :size => '20x20' ), appointment_path(appointment4.id), class: "appt-red-btn" %></td>
        <td><%= link_to image_tag('gomi.jpg', :size => '20x20' ), appointment_path(appointment4.id), method: :delete, class: "delete-btn",data: { confirm: '削除しますか？' } %>
        </td>
      </tr>
      <% end %>
    </table>

  </div>
  <%= render "shared/footer" %>
</div>

app/views/appointments/show.html.erb
<div class="relative">
  <%= render "shared/header" %>

  <div class="input-contents">  
    <div class="input-main">
      <h2 class="input-title"><%= @appointment.company %></h2>
   
      <%# アポ情報 %>
      <div class="new-appt">
        <div class="weight-bold-text">
          約束日:
          <%=  @appointment.appt_date %>
        </div>
        <div class="weight-bold-text">
          点数
          <%= @appointment.score %>点
        </div>
      </div>
      
      <%# チェックリスト%> 
      <table class='table-check'>
        <tr class='check-list-title'><th colspan="4"><%= @appointment.check.title%></th></tr>
        <tr class='check-list'><th class="th-title"><%="チェック項目" %></th><th><%="自己採点" %></th><th><%="上長採点" %></th><th><%="差分" %></th></tr>
        <% unless @appointment.nil?%>
        <tr><td><%= @appointment.check.item1%></td><td><%=@appointment.point1 %>点</td><td><% unless @evaluation.nil?%><%=@evaluation.point1 %><%end%>点</td><td><%= def_point1 %>点</td></tr>
        <tr><td><%= @appointment.check.item2%></td><td><%=@appointment.point2 %>点</td><td><% unless @evaluation.nil?%><%=@evaluation.point2 %><%end%>点</td><td><%= def_point2 %>点</td></tr>
        <tr><td><%= @appointment.check.item3%></td><td><%=@appointment.point3 %>点</td><td><% unless @evaluation.nil?%><%=@evaluation.point3 %><%end%>点</td><td><%= def_point3 %>点</td></tr>
        <tr><td><%= @appointment.check.item4%></td><td><%=@appointment.point4 %>点</td><td><% unless @evaluation.nil?%><%=@evaluation.point4 %><%end%>点</td><td><%= def_point4 %>点</td></tr>
        <tr><td><%= @appointment.check.item5%></td><td><%=@appointment.point5 %>点</td><td><% unless @evaluation.nil?%><%=@evaluation.point5 %><%end%>点</td><td><%= def_point5 %>点</td></tr>
        <tr><td><%= @appointment.check.item6%></td><td><%=@appointment.point6 %>点</td><td><% unless @evaluation.nil?%><%=@evaluation.point6 %><%end%>点</td><td><%= def_point6 %>点</td></tr>
        <tr><td><%= @appointment.check.item7%></td><td><%=@appointment.point7 %>点</td><td><% unless @evaluation.nil?%><%=@evaluation.point7 %><%end%>点</td><td><%= def_point7 %>点</td></tr>
        <tr><td><%= @appointment.check.item8%></td><td><%=@appointment.point8 %>点</td><td><% unless @evaluation.nil?%><%=@evaluation.point8 %><%end%>点</td><td><%= def_point8 %>点</td></tr>
        <tr><td><%= @appointment.check.item9%></td><td><%=@appointment.point9 %>点</td><td><% unless @evaluation.nil?%><%=@evaluation.point9 %><%end%>点</td><td><%= def_point9 %>点</td></tr>
        <tr><td><%= @appointment.check.item10%></td><td><%=@appointment.point10 %>点</td><td><% unless @evaluation.nil?%><%=@evaluation.point10 %><%end%>点</td><td><%= def_point10 %>点</td></tr>
        <tr><td><%= @appointment.check.item11%></td><td><%=@appointment.point11 %>点</td><td><% unless @evaluation.nil?%><%=@evaluation.point11 %><%end%>点</td><td><%= def_point11 %>点</td></tr>
        <tr><td><%= @appointment.check.item12%></td><td><%=@appointment.point12 %>点</td><td><% unless @evaluation.nil?%><%=@evaluation.point12 %><%end%>点</td><td><%= def_point12 %>点</td></tr>
        <tr><td><%= @appointment.check.item13%></td><td><%=@appointment.point13 %>点</td><td><% unless @evaluation.nil?%><%=@evaluation.point13 %><%end%>点</td><td><%= def_point13 %>点</td></tr>
        <tr><td><%= @appointment.check.item14%></td><td><%=@appointment.point14 %>点</td><td><% unless @evaluation.nil?%><%=@evaluation.point14 %><%end%>点</td><td><%= def_point14 %>点</td></tr>
        <tr><td><%= @appointment.check.item15%></td><td><%=@appointment.point15 %>点</td><td><% unless @evaluation.nil?%><%=@evaluation.point15 %><%end%>点</td><td><%= def_point15 %>点</td></tr>
        <tr><td><%= @appointment.check.item16%></td><td><%=@appointment.point16 %>点</td><td><% unless @evaluation.nil?%><%=@evaluation.point16 %><%end%>点</td><td><%= def_point16 %>点</td></tr>
        <tr><td><%= @appointment.check.item17%></td><td><%=@appointment.point17 %>点</td><td><% unless @evaluation.nil?%><%=@evaluation.point17 %><%end%>点</td><td><%= def_point17 %>点</td></tr>
        <tr><td><%= @appointment.check.item18%></td><td><%=@appointment.point18 %>点</td><td><% unless @evaluation.nil?%><%=@evaluation.point18 %><%end%>点</td><td><%= def_point18 %>点</td></tr>
        <tr><td><%= @appointment.check.item19%></td><td><%=@appointment.point19 %>点</td><td><% unless @evaluation.nil?%><%=@evaluation.point19 %><%end%>点</td><td><%= def_point19 %>点</td></tr>
        <tr><td><%= @appointment.check.item20%></td><td><%=@appointment.point20 %>点</td><td><% unless @evaluation.nil?%><%=@evaluation.point20 %><%end%>点</td><td><%= def_point20 %>点</td></tr>
        <%end%>
      </table>

      <div class="weight-bold-text">
        振り返り
        <div class="m-comment"><%= @appointment.comment%></div>
        <div class="weight-bold-text">
        上長コメント
        </div>
        <div class="m-comment"><% unless @evaluation.nil? %><%=  @evaluation.comment%><%end%></div>
      </div>
      
      <div class="input-btn-contents">
        <%=link_to 'もどる', :back, class:"back-btn" %>
      </div>

    </div>
  </div>

  <%= render "shared/footer" %>
</div>